### PR TITLE
Updates formatting of README.rst

### PR DESCRIPTION
**Pull request by funkyfuture**
this is mainly about formatting.

but let me raise an issue here. i understand why you moved the configuration section up and it makes sense. but now the usage part is fragmented and rather confusing. what about splitting the obtaining/building/installation stuff out to an `INSTALL.rst`?

### CODE REVIEW

**Comment by lpodl** [comment]
Lets have at least the standard user case completely documented in the ``README.rst``.
So obtaining as a zip package should be covered, while building one and the "classic" installation are moved into an ``INSTALL.rst``

**Comment by funkyfuture** [comment]
makes sense, so the toc would be:

- what it is / does
- quick start
  - download (and alias? the details take quiet some space)
  - base config
  - magic

does this make sense too?

**Comment by lpodl** [comment]
Yes, lets include the alias section so day-to-day users dont have to bother with changing directories.
If "magic" is the same as "usage" to you, I agree.
A short reference to ``INSTALL.rst`` prior to the download section should be fine.

**Review by lpodl — APPROVED** [review]
This should be an upgrade for the common user.
I'll merge these changes into master as this is what we discussed.

**Pull request merged**
